# -*- coding: utf-8 -*-
"""DataScienceWeek5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/sanvidesai/datascienceweek5.920578c5-17de-498a-a9cd-f2f3e16324cd.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260627/auto/storage/goog4_request%26X-Goog-Date%3D20260627T110542Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D9c935f623c53eff100551bdd74748f43e36282d3b0257757436f56c32090c66c6c88e4d9fb7479872dbc45e37a0736627d55472cd5e9b327bc6bd4faa0e999dcaf722674128ae0b97ea0b9e8fc7cb58d1dfa0ab95bc81cccce4ee3f255cf5a55fbadf8652f93b0dfdeea9c2e0c0ef0a2231e8381f7f6ff2564a400939210b879c765d84a78854e06a5b3e2a68e42ed6e2666a34ba7bbb5fc5b57eab61a0b21f089ff6c59e7c65c18a04673c324fbcc9812fe7521c31c5753f9a0479ee06d6e66136db86debc967b7e9b75325ec88e273c0a9c5c9611d34691e21808bd9e042715088787eead0b641df5e70421fb3505e966b98574c3bc778fbcc2b00d6efb738
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
bhavikjikadara_car_price_prediction_dataset_path = kagglehub.dataset_download('bhavikjikadara/car-price-prediction-dataset')

print('Data source import complete.')

import pandas as pd

"""**Task 1**"""

df = pd.read_csv("/kaggle/input/datasets/bhavikjikadara/car-price-prediction-dataset/car_prediction_data.csv")
#loading the dataset

df.head(5)
#first five rows

df.tail(5)
#last five rows

df.shape
#shape of dataset

df.columns
#names of columns

df.dtypes
#datatypes

"""**Task 2**"""

df.info()

df.describe()

df.isna().sum()
#missing values

df.duplicated().sum()
#duplicate rows

df.drop_duplicates(inplace = True)
#dropping duplicates

"""**Task 3**"""

df['Fuel_Type'].unique()

df['Fuel_Type_int'] = df['Fuel_Type'].apply(lambda x : 0 if x == 'Petrol' else 1 if x == 'Diesel' else 2)

df['Seller_Type_int'] = df['Seller_Type'].apply(lambda x : 0 if x == 'Dealer' else 1)

df['Transmission_int'] = df['Transmission'].apply(lambda x : 0 if x == 'Manual' else 1)

df.drop(columns = ['Car_Name', 'Fuel_Type', 'Seller_Type', 'Transmission'], inplace = True)

X = df.drop(columns = ['Selling_Price'])
y = df['Selling_Price']

"""**Task 4**"""

df.columns

import matplotlib.pyplot as plt

plt.hist(df['Present_Price'], bins = 20)
plt.title('Car Prices')
plt.xlabel('Price of car')
plt.ylabel('Number of cars')
plt.show()

plt.scatter(df['Kms_Driven'], df['Present_Price'], color = 'blue', marker = '*')
plt.xlabel('Mileage')
plt.ylabel('Present Price')
plt.title('Mileage vs Price scatterplot')
plt.show()

plt.scatter(df['Year'], df['Present_Price'], color = 'green', marker = '.')
plt.title('Year vs price scatterplot')
plt.xlabel('Year')
plt.ylabel('Price')
plt.show()

fuel_counts = df['Fuel_Type_int'].value_counts().sort_index()
plt.bar(fuel_counts.index.astype(str), fuel_counts.values)
plt.title('Fuel Types')
plt.xlabel('Type of fuel')
plt.ylabel('Number of cars')
plt.xticks(['0', '1', '2'], ['Petrol', 'Diesel', 'CNG'])
plt.show()

corr = df.corr(numeric_only = True)
plt.imshow(corr, cmap = 'coolwarm', interpolation = 'nearest')
plt.colorbar(label = 'Correlation')
plt.title('Correlation heatmap')
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.show()

plt.boxplot(df['Present_Price'])
plt.title("Box Plot of Present Price")
plt.ylabel("Present Price")
plt.show()

plt.boxplot(df['Selling_Price'])
plt.title("Box Plot of Selling Price")
plt.ylabel("Selling Price")
plt.show()

"""**Task 5**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

"""**Task 6**"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""**Task 7**"""

from sklearn.metrics import mean_absolute_error
print("Mean Absolute Error (MAE): ")
print(mean_absolute_error(y_test, y_pred))

from sklearn.metrics import mean_squared_error
print("Mean Squared Error(MSE): ")
print(mean_squared_error(y_test, y_pred))

print("Root Mean Squared Error(RMSE): ")
print(mean_squared_error(y_test, y_pred) ** 0.5)

from sklearn.metrics import r2_score
print("R2 Score: ")
print(r2_score(y_test, y_pred))

"""**Task 8**"""

sample = X_test[0].reshape(1, -1)
predicted_price = model.predict(sample)
print("Predicted Price: ", predicted_price[0])
print("Actual Price: ", y_test.iloc[0])